In [8]:
import torch

In [9]:
randint = torch.randint(-200, 200, (6,))
randint

tensor([ 184,  176, -119,   51,   79,  117])

In [13]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
linspace = torch.linspace(10, 100, 29)
linspace

tensor([ 10.0000,  13.2143,  16.4286,  19.6429,  22.8571,  26.0714,  29.2857,
         32.5000,  35.7143,  38.9286,  42.1429,  45.3571,  48.5714,  51.7857,
         55.0000,  58.2143,  61.4286,  64.6429,  67.8571,  71.0714,  74.2857,
         77.5000,  80.7143,  83.9286,  87.1429,  90.3571,  93.5714,  96.7857,
        100.0000])